### PR TITLE
Set OPEN_TIMEOUT to 30

### PR DESCRIPTION
**Pull request by tsujigiri**
Apparently 5 was a bit too short, let's try 30.

### CODE REVIEW

**Comment by RKushnir** [comment]
It may make sense to allow user to pass value. That way you can experiment with it without updating the gem each time.

**Comment by dziemba** [comment]
> It may make sense to allow user to pass value.

I don't agree. The gem should pick a reasonable number and not expose those problems to the end-user IMHO. And for testing to get the number in the gem right, we can always temporarily monkey-patch the class in our apps.

**Comment by tsujigiri** [comment]
In the long run, I am hoping Easybill fixes the issue, so I'd rather not make this configurable in the first place.

**Comment by RKushnir** [comment]
My motivation for making it configurable is simple — it's easier to update
the app, than update the gem and also the app. And the "end user" is only
us :) If you're sure timeout won't need to be adjusted every week, I'm fine
with the constant.

**Comment by tsujigiri** [comment]
I don't think it will. The 30s will allow finance to work again, I will send Easybill a more detailed picture of what's going on on our side so they can hopefully fix it.

**Pull request merged**
